routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as' => 'home', 'uses' => 'AppControllers\IndexController@index']);
Route::put('/', ['as' => 'home.store', 'uses' => 'AppControllers\IndexController@store']);

app/Application.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Application extends Model
{
    /**
     * Связанная с моделью таблица.
     *
     * @var string
     */
    protected $table = 'applications';

    protected $fillable = ['email', 'text'];

    public function getCreatedAtAttribute($attr)
    {
        $Carbon = new Carbon($attr);
        $createdAt = $Carbon->format('d.m.Y');
        return $createdAt;
    }

    public function scopeEmail($query, $email)
    {
        return $query->where('email', '=', $email);
    }

    public function scopeGetAll($query)
    {
        return $query->where('id', '!=', 0)->orderBy('id','desc');
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/AppControllers/IndexController.php
<?php

namespace App\Http\Controllers\AppControllers;

use Validator;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller as Controller;
use App\Application;

class IndexController extends Controller
{
    public function __construct()
    {
        $this->middleware('guest');
    }

    public function index(Application $applicationModel)
    {
        $rows = $applicationModel->getAll()->get();

        return view('app.index', ['rows' => $rows]);
    }

    /**
     * Сохранить заявку.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Application $applicationModel, Request $request)
    {

        $validator = Validator::make($request->all(), [
            'email' => 'required|string|email',
            'text' => 'string|max:5000',
        ]);

        if ($validator->fails()) {
            // Переданные данные не прошли проверку
            $messages = $validator->messages();

            if ($request->ajax()) {
                return ['errors' => $messages];
            }

            return redirect('/')->withErrors($validator)->withInput($request->all());
        }
        else {
            $applicationModel->email($request->input('email'))->delete();
            $rows = $applicationModel->create($request->all())->getAll()->get();

            if ($request->ajax()) {
                return ['data' => $rows];
            }

            return redirect('/');
        }

    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/app/index.blade.php
@extends('base')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">

                @if ( isset($rows) && count($rows) )
                    <div class="panel panel-default" v-if="!rows">
                        <div class="panel-heading">@lang('messages.panel_title')</div>
                        <div class="panel-body">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th class="col-md-2">@lang('messages.table_th_n')</th>
                                        <th class="col-md-8">@lang('messages.table_th_user')</th>
                                        <th class="col-md-4">@lang('messages.table_th_date')</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach($rows as $item)
                                        <tr>
                                            <td>{{ $item->id }}</td>
                                            <td>{{ $item->email }}</td>
                                            <td>{{ $item->created_at }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                @endif

                <rows-applications v-if="rows"
                                  :rows="rows"
                                  panel_title="@lang('messages.panel_title')"
                                  thn="@lang('messages.table_th_n')"
                                  thuser="@lang('messages.table_th_user')"
                                  thdate="@lang('messages.table_th_date')">

                </rows-applications>

                <div class="panel panel-default">
                    <div class="panel-heading">@lang('messages.panel_title_form')</div>
                    <div class="panel-body">
                        {!! Form::open(['route' => 'home.store', 'method' => 'put', 'v-on:submit.prevent' => 'onSubmit']) !!}
                        <div class="form-group {{ $errors->first('email') ? 'has-error' : '' }}"
                             v-bind:class="{ 'has-error': $v.email.$error }">
                            {!! Form::label('email', trans('messages.field_label_email'), ['class' => 'required control-label']) !!}
                            {!! Form::email('email', isset($request) ? $request['email'] : null, ['class' => 'form-control', 'v-model.trim' => "email", '@input' => '$v.email.$touch()' ]) !!}
                            <label-danger v-if="!$v.email.email" lang="@lang('messages.email')"></label-danger>
                            @if ($errors->first('email')) <span
                                    class="label label-danger">{{ $errors->first('email') }}</span> @endif
                        </div>
                        <div class="form-group {{ $errors->first('text') ? 'has-error' : '' }}"
                             v-bind:class="{ 'has-error': $v.text.$error }">
                            {!! Form::label('text', trans('messages.field_label_text'), ['class' => 'control-label']) !!}
                            {!! Form::textarea('text', isset($request) ? $request['text'] : null, ['class' => 'form-control', 'maxlength' => 5000, 'rows' => 3, 'v-model.trim' => "text", '@input' => '$v.text.$touch()']) !!}
                            @if ($errors->first('text'))
                                <span class="label label-danger">{{ $errors->first('text') }}</span>
                            @else
                                <span class="label"
                                      v-bind:class="{ 'label-danger': $v.text.$error, 'label-success': !$v.text.$error}">@lang('messages.count', ['count' => '@{{ count }}' ])</span>
                            @endif
                        </div>
                        <div class="form-group clearfix" v-if="!$v.text.$error">
                            {!! Form::submit(trans('messages.btn_submit_send'), ['class' => 'btn btn-primary pull-right', ':class' => "{ 'disabled': disabled }", ':disabled' => 'disabled']) !!}
                        </div>
                        {!! Form::close() !!}

                    </div>

                </div>
                <transition name="fade">
                    <alert-success v-if="success" message="@lang('messages.application_success')"></alert-success>
                    <alert-error v-if="error" message="@lang('messages.error')"></alert-error>
                </transition>
            </div>
        </div>
    </div>

@stop

resources/views/base.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>
        <!-- Styles -->
        <link href="/css/app.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div id="app">
            @yield('content')
        </div>

        <script>
            window.Laravel = {
                "csrfToken": <?= json_encode(csrf_token()) ?>
            }
        </script>
        <script src="/js/app.js"></script>
    </body>
</html>